setwd("C:/Users/Public/Documents/R Workspace/Exploratory Data")
dt <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
library(dplyr)
dataSet <- filter(dt, Date %in% c("1/2/2007","2/2/2007"))#Data.Frame
TimeHour <- strptime(paste(dataSet$Date, dataSet$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
Energy1 <- as.numeric(dataSet$Sub_metering_1)
Energy2 <- as.numeric(dataSet$Sub_metering_2)
Energy3 <- as.numeric(dataSet$Sub_metering_3)

png("plot3.png", width=480, height=480)
plot(TimeHour, Energy1, xlab = "", ylab = "Energy sub meteing", type = "l")
lines(TimeHour,Energy2, type = "l", col = "red")
lines(TimeHour,Energy3, type = "l", col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()
